
# SA 17.5 — Field Validation Framework and Ecological Indicator Integration

**Project:** Environmental Data Cube for Oglala Lakota  
**Study Area:** Ate Makoce - BIA Parcel, Pine Ridge Indian Reservation  
**Research Focus:** Agricultural sustainability assessment using remote sensing, ecological field indicators, and Tribal Data Sovereignty principles.

---

## 1. Research Framework

The purpose of this research framework is to connect satellite-derived vegetation-change observations with independent ecological field measurements and authorized grazing-management information. This integration is intended to support a scientifically rigorous and culturally appropriate assessment of agricultural sustainability.

The framework consists of five interconnected stages:

### Stage 1 — Environmental Data Cube

**Existing research evidence:**
- Landsat-derived NDVI and NDMI vegetation indices.
- Vegetation-change trajectories for 2019, 2022, and 2023.
- Original growing-season and July–August composite comparisons.
- Climate context, including temperature and precipitation.
- Spatial classification of vegetation decline and recovery.

**Purpose:** Identify spatial and temporal patterns of vegetation condition and change within the study parcel.

### Stage 2 — Provisional Field-Validation Sampling

**Sampling framework:**
- 30 provisional field-validation candidates.
- Five vegetation-response strata.
- Six candidates allocated to each original stratum.
- Minimum spatial separation and parcel-boundary clearance evaluated.
- Seasonal classification sensitivity documented.

**Purpose:** Establish spatially distributed candidate locations for independent ecological observations.

The sampling locations remain provisional and are not authorized field sites.

### Stage 3 — Ecological Field Indicators

| Domain | Proposed indicator | Measurement approach |
|---|---|---|
| Vegetation | Vegetation cover (%) | Line-point intercept |
| Vegetation | Aboveground forage biomass (kg dry matter/ha) | Quadrat sampling and dry-weight measurement |
| Vegetation | Plant species composition | Species-level field survey |
| Soil | Bare ground (%) | Line-point intercept |
| Soil | Soil surface condition | Standardized surface assessment |
| Soil | Visible erosion indicators | Rill, pedestal, and soil movement observations |
| Grazing | Forage utilization (%) | Approved utilization protocol |
| Management | Stocking and grazing history | Authorized management records |

**Purpose:** Provide independent ecological evidence to evaluate and contextualize remotely sensed vegetation patterns.

These measurements are proposed; field observations have not yet been collected or integrated.

### Stage 4 — Tribal Data Sovereignty and Research Governance

Research activities must incorporate appropriate Tribal governance, cultural protocols, and data stewardship requirements.

**Key considerations:**
- Obtain appropriate Tribal authorization before field activities.
- Establish approved protocols for collecting ecological and management information.
- Determine permissions for accessing and using grazing-management records.
- Establish requirements for data storage, access, analysis, publication, and sharing.
- Protect sensitive land-management and culturally significant information.
- Incorporate community-approved ecological reference conditions and assessment criteria.

**Purpose:** Ensure that research methods and data practices respect the rights, authority, and priorities of the Oglala Lakota Nation.

### Stage 5 — Integrated Agricultural Sustainability Assessment

The final assessment will integrate:

1. **Remote sensing evidence:** Vegetation-index changes, spatial patterns, and recovery trajectories.
2. **Climate context:** Precipitation and temperature conditions associated with the observation periods.
3. **Ecological field evidence:** Vegetation cover, forage biomass, species composition, and soil condition.
4. **Management context:** Authorized grazing records and land-management information.
5. **Research governance:** Tribal authorization, data stewardship, and approved assessment criteria.

**Purpose:** Develop an evidence-based understanding of agricultural sustainability that considers vegetation dynamics, ecological conditions, climate variability, and land-management context.

An overall agricultural sustainability rating cannot be assigned until sufficient independent ecological evidence, management information, and appropriate reference criteria are available.

---

## 2. Research Framework Diagram

```text
          ENVIRONMENTAL DATA CUBE FOR OGLALA LAKOTA
          ----------------------------------------
             Landsat NDVI / NDMI
             Climate Context
             Vegetation-Change Trajectories
                          |
                          v
             PROVISIONAL FIELD SAMPLING
             --------------------------
             30 Candidate Locations
             5 Vegetation-Response Strata
             Seasonal Classification QA
                          |
                          v
              ECOLOGICAL FIELD VALIDATION
              ---------------------------
              Vegetation Cover and Biomass
              Plant Species Composition
              Bare Ground and Soil Condition
              Erosion Indicators
                          |
                          v
              INTEGRATION WITH MANAGEMENT
              ---------------------------
              Authorized Grazing Records
              Stocking and Utilization Data
              Ecological Reference Conditions
                          |
                          v
             AGRICULTURAL SUSTAINABILITY
                     ASSESSMENT
             ---------------------------
             Integrated Evidence
             Uncertainty Evaluation
             Management-Relevant Findings

    TRIBAL DATA SOVEREIGNTY AND RESEARCH GOVERNANCE
    ------------------------------------------------
    Applies throughout all stages of the framework.
```

---

## 3. Current Research Status

| Research component | Status |
|---|---|
| Landsat vegetation-change analysis | Completed for selected years |
| Seasonal composite sensitivity analysis | Completed |
| Classification equivalence audit | Completed |
| Provisional sampling design | Completed |
| Spatial sampling QA | Passed for 30 candidates |
| Seasonal classification stability | 15 of 30 candidates stable |
| Ecological field measurements | Not collected |
| Authorized grazing records | Not integrated |
| Ecological reference criteria | Not established |
| Tribal field authorization | Not documented |
| Integrated sustainability assessment | Pending |

---

## 4. Methodological Considerations

The remote-sensing analyses demonstrate consistent parcel-average vegetation-index decline from 2019 to 2022, followed by partial recovery in 2023. However, discrete vegetation-response classifications exhibit sensitivity to seasonal compositing choices.

These findings establish the importance of independent field observations and uncertainty evaluation.

NDVI and NDMI changes should not be interpreted as direct evidence of overgrazing, livestock impacts, or agricultural sustainability without supporting ecological and management information.

Furthermore, the provisional stratified candidate sample is not a probability sample and should not be treated as statistically representative of all parcel conditions without additional sampling-design justification.

---

## 5. Expected Research Contribution

This framework is intended to support an integrated agricultural sustainability assessment for the Oglala Lakota Nation by combining geospatial analysis, ecological field evidence, and appropriate research governance.

The anticipated contribution is a reproducible methodology for evaluating vegetation and rangeland conditions while recognizing climate variability, methodological uncertainty, Tribal Data Sovereignty, and the importance of locally appropriate ecological reference conditions.

**Next Research Stage:** SA 17.5.1 — Field Validation Framework and Indicator Register.

In [121]:
# =============================================================================
# SA 17.5.1 — FIELD VALIDATION FRAMEWORK AND INDICATOR REGISTER
# Environmental Data Cube for Oglala Lakota
# Ate Makoce - BIA Parcel
#
# PURPOSE:
# Connect 30 provisional candidate locations to proposed ecological
# indicators, seasonal QA, and Tribal Data Sovereignty requirements.
#
# No field observations are invented.
# No existing objects are overwritten.
# No files are created or modified.
# =============================================================================

import numpy as np
import pandas as pd
from IPython.display import display

print("=" * 78)
print("SA 17.5.1 — FIELD VALIDATION FRAMEWORK")
print("=" * 78)

# -------------------------------------------------------------------------
# 1. VERIFY EXISTING RESEARCH OBJECTS
# -------------------------------------------------------------------------

required = [
    "sa17_sampling_revised",
    "sa16_17_6_candidate_review",
    "sa16_17_6_stratum_stability"
]

missing = [name for name in required if name not in globals()]

if missing:
    raise RuntimeError(
        "Required notebook objects missing: " + ", ".join(missing)
    )

candidates = sa17_sampling_revised.copy()
qa = sa16_17_6_candidate_review.copy()

if len(candidates) != 30:
    raise ValueError("Expected 30 provisional candidates.")

if candidates["Candidate_ID"].duplicated().any():
    raise ValueError("Duplicate candidate IDs.")

if qa["Candidate_ID"].duplicated().any():
    raise ValueError("Duplicate IDs in QA register.")

# -------------------------------------------------------------------------
# 2. DEFINE PROPOSED ECOLOGICAL INDICATORS
# -------------------------------------------------------------------------

indicator_records = [
    {
        "Indicator_ID": "VEG-01",
        "Domain": "Vegetation",
        "Indicator": "Vegetation cover",
        "Proposed_Unit": "%",
        "Proposed_Method": "Line-point intercept",
        "Cube_Relationship": "NDVI",
        "Evidence_Status": "Not collected",
        "Governance": "Field authorization required"
    },
    {
        "Indicator_ID": "VEG-02",
        "Domain": "Vegetation",
        "Indicator": "Aboveground forage biomass",
        "Proposed_Unit": "kg dry matter/ha",
        "Proposed_Method": "Quadrat clipping and dry-weight measurement",
        "Cube_Relationship": "NDVI",
        "Evidence_Status": "Not collected",
        "Governance": "Field authorization required"
    },
    {
        "Indicator_ID": "VEG-03",
        "Domain": "Vegetation",
        "Indicator": "Plant species composition",
        "Proposed_Unit": "% cover by species",
        "Proposed_Method": "Species-level field survey",
        "Cube_Relationship": "NDVI contextual interpretation",
        "Evidence_Status": "Not collected",
        "Governance": "Field authorization required"
    },
    {
        "Indicator_ID": "SOIL-01",
        "Domain": "Soil",
        "Indicator": "Bare ground",
        "Proposed_Unit": "%",
        "Proposed_Method": "Line-point intercept",
        "Cube_Relationship": "NDVI and exposed-ground context",
        "Evidence_Status": "Not collected",
        "Governance": "Field authorization required"
    },
    {
        "Indicator_ID": "SOIL-02",
        "Domain": "Soil",
        "Indicator": "Soil surface condition",
        "Proposed_Unit": "Protocol-defined observations",
        "Proposed_Method": "Standardized soil surface assessment",
        "Cube_Relationship": "NDMI contextual interpretation",
        "Evidence_Status": "Not collected",
        "Governance": "Field authorization required"
    },
    {
        "Indicator_ID": "SOIL-03",
        "Domain": "Soil",
        "Indicator": "Visible erosion indicators",
        "Proposed_Unit": "Protocol-defined observations",
        "Proposed_Method": "Rill, pedestal, and soil movement assessment",
        "Cube_Relationship": "Independent condition evidence",
        "Evidence_Status": "Not collected",
        "Governance": "Field authorization required"
    },
    {
        "Indicator_ID": "GRAZE-01",
        "Domain": "Grazing",
        "Indicator": "Forage utilization",
        "Proposed_Unit": "%",
        "Proposed_Method": "Approved utilization protocol",
        "Cube_Relationship": "Management interpretation",
        "Evidence_Status": "Not collected",
        "Governance": "Authorization and protocol approval required"
    },
    {
        "Indicator_ID": "GRAZE-02",
        "Domain": "Grazing",
        "Indicator": "Stocking and grazing history",
        "Proposed_Unit": "Protocol-defined",
        "Proposed_Method": "Authorized management records",
        "Cube_Relationship": "Grazing pressure context",
        "Evidence_Status": "Not integrated",
        "Governance": "Data access and use approval required"
    }
]

sa17_5_indicator_register = pd.DataFrame(indicator_records)

print("\n1. PROPOSED ECOLOGICAL INDICATOR REGISTER")
print("-" * 78)

display(sa17_5_indicator_register)

# -------------------------------------------------------------------------
# 3. CREATE PROVISIONAL FIELD PLANNING REGISTER
# -------------------------------------------------------------------------

qa_columns = [
    "Candidate_ID",
    "Original_Stratum",
    "Summer_Stratum",
    "Stratum_Stable",
    "Review_Priority",
    "Original_Min_Threshold_Distance",
    "Summer_Min_Threshold_Distance"
]

missing_columns = [
    col for col in qa_columns if col not in qa.columns
]

if missing_columns:
    raise RuntimeError(
        "Missing QA columns: " + ", ".join(missing_columns)
    )

field_plan = candidates.merge(
    qa[qa_columns],
    on="Candidate_ID",
    how="left",
    validate="one_to_one",
    suffixes=("", "_QA")
)

if len(field_plan) != 30:
    raise ValueError("Candidate count changed during merge.")

if field_plan["Review_Priority"].isna().any():
    raise ValueError("Some candidates lack QA review priorities.")

# -------------------------------------------------------------------------
# 4. ADD PLANNING AND GOVERNANCE FIELDS
# -------------------------------------------------------------------------

field_plan["Field_Status"] = "Provisional — not visited"

field_plan["Site_Authorization"] = "Not documented"

field_plan["Protocol_Approval"] = "Not documented"

field_plan["Data_Governance_Status"] = (
    "Tribal review and authorization required"
)

field_plan["Field_Observation_Status"] = "Not collected"

field_plan["Ecological_Reference_Status"] = (
    "Reference criteria not established"
)

field_plan["Grazing_Record_Status"] = (
    "Authorized records not integrated"
)

field_plan["Field_Validation_Complete"] = False

field_plan["Agricultural_Sustainability_Rating"] = pd.NA

field_plan["Planning_Recommendation"] = np.where(
    field_plan["Stratum_Stable"],
    "Retain candidate; document seasonal QA",
    "Retain candidate; review seasonal classification"
)

sa17_5_field_planning_register = field_plan.copy()

# -------------------------------------------------------------------------
# 5. DISPLAY FIELD PLANNING REGISTER
# -------------------------------------------------------------------------

print("\n2. FIELD VALIDATION PLANNING REGISTER")
print("-" * 78)

display(
    sa17_5_field_planning_register[
        [
            "Candidate_ID",
            "Original_Stratum",
            "Summer_Stratum",
            "Stratum_Stable",
            "Review_Priority",
            "Field_Status",
            "Site_Authorization",
            "Field_Observation_Status",
            "Planning_Recommendation"
        ]
    ]
)

# -------------------------------------------------------------------------
# 6. SUMMARIZE INDICATOR COVERAGE
# -------------------------------------------------------------------------

print("\n3. INDICATOR COVERAGE")
print("-" * 78)

display(
    sa17_5_indicator_register.groupby(
        ["Domain", "Evidence_Status"]
    ).size().reset_index(name="Indicator_Count")
)

print("\n4. SAMPLING AND GOVERNANCE STATUS")
print("-" * 78)

print(f"Provisional candidates: {len(field_plan)}")
print(
    "Stable strata: "
    f"{int(field_plan['Stratum_Stable'].sum())}"
)
print(
    "Changed strata: "
    f"{int((~field_plan['Stratum_Stable']).sum())}"
)
print(
    "Field observations collected: "
    f"{int(field_plan['Field_Validation_Complete'].sum())}"
)
print(
    "Proposed ecological indicators: "
    f"{len(sa17_5_indicator_register)}"
)

# -------------------------------------------------------------------------
# 7. RESEARCH INTERPRETATION
# -------------------------------------------------------------------------

print("\n5. RESEARCH INTERPRETATION")
print("-" * 78)

print("""
The field-validation framework links 30 provisional sampling
candidates to eight proposed ecological and grazing-management
indicators.

Candidate locations retain their original recovery-stratum
assignments, while seasonal classification stability and review
priority are maintained as separate quality-assurance attributes.

No independent field measurements or authorized grazing records
have been integrated. Consequently, the proposed indicators
cannot yet be used to validate vegetation recovery categories,
attribute observed changes to grazing, or assign agricultural
sustainability ratings.

Subsequent work requires approved field methods, appropriate
Tribal authorization, ecological reference criteria, and
independent observations.
""".strip())

print("\n6. REPRODUCIBILITY AND DATA GOVERNANCE")
print("-" * 78)

print("Existing candidate coordinates preserved.")
print("Original sampling allocation preserved.")
print("No field measurements invented.")
print("No sustainability ratings assigned.")
print("No files created or modified.")
print("New registers exist only in notebook memory.")

print("\nSA 17.5.1 COMPLETE")

==============================================================================
SA 17.5.1 — FIELD VALIDATION FRAMEWORK
==============================================================================

1. PROPOSED ECOLOGICAL INDICATOR REGISTER
------------------------------------------------------------------------------

,Indicator_ID,Domain,Indicator,Proposed_Unit,Proposed_Method,Cube_Relationship,Evidence_Status,Governance
0,VEG-01,Vegetation,Vegetation cover,%,Line-point intercept,NDVI,Not collected,Field authorization required
1,VEG-02,Vegetation,Aboveground forage biomass,kg dry matter/ha,Quadrat clipping and dry-weight measurement,NDVI,Not collected,Field authorization required
2,VEG-03,Vegetation,Plant species composition,% cover by species,Species-level field survey,NDVI contextual interpretation,Not collected,Field authorization required
3,SOIL-01,Soil,Bare ground,%,Line-point intercept,NDVI and exposed-ground context,Not collected,Field authorization required
4,SOIL-02,Soil,Soil surface condition,Protocol-defined observations,Standardized soil surface assessment,NDMI contextual interpretation,Not collected,Field authorization required
5,SOIL-03,Soil,Visible erosion indicators,Protocol-defined observations,"Rill, pedestal, and soil movement assessment",Independent condition evidence,Not collected,Field authorization required
6,GRAZE-01,Grazing,Forage utilization,%,Approved utilization protocol,Management interpretation,Not collected,Authorization and protocol approval required
7,GRAZE-02,Grazing,Stocking and grazing history,Protocol-defined,Authorized management records,Grazing pressure context,Not integrated,Data access and use approval required

2. FIELD VALIDATION PLANNING REGISTER
------------------------------------------------------------------------------

,Candidate_ID,Original_Stratum,Summer_Stratum,Stratum_Stable,Review_Priority,Field_Status,Site_Authorization,Field_Observation_Status,Planning_Recommendation
0,AM-01,0,0,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
1,AM-02,0,3,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
2,AM-03,0,4,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
3,AM-04,0,2,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
4,AM-05,0,0,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
5,AM-06,0,4,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
6,AM-07,1,4,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
7,AM-08,1,2,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
8,AM-09,1,2,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
9,AM-10,1,4,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
10,AM-11,1,2,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
11,AM-12,1,2,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
12,AM-13,2,2,True,Priority 4 — Stable / farther from boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
13,AM-14,2,2,True,Priority 4 — Stable / farther from boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
14,AM-15,2,2,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
15,AM-16,2,2,True,Priority 4 — Stable / farther from boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
16,AM-17,2,2,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
17,AM-18,2,2,True,Priority 4 — Stable / farther from boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
18,AM-19,3,3,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
19,AM-20,3,3,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
20,AM-21,3,3,True,Priority 4 — Stable / farther from boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
21,AM-22,3,3,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
22,AM-23,3,4,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
23,AM-24,3,3,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
24,AM-25,4,3,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
25,AM-26,4,4,True,Priority 3 — Stable / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA
26,AM-27,4,3,False,Priority 2 — Changed / other sensitivity,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
27,AM-28,4,2,False,Priority 1 — Changed / near boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
28,AM-29,4,3,False,Priority 2 — Changed / other sensitivity,Provisional — not visited,Not documented,Not collected,Retain candidate; review seasonal classification
29,AM-30,4,4,True,Priority 4 — Stable / farther from boundary,Provisional — not visited,Not documented,Not collected,Retain candidate; document seasonal QA

3. INDICATOR COVERAGE
------------------------------------------------------------------------------

       Domain Evidence_Status  Indicator_Count
0     Grazing   Not collected                1
1     Grazing  Not integrated                1
2        Soil   Not collected                3
3  Vegetation   Not collected                3

4. SAMPLING AND GOVERNANCE STATUS
------------------------------------------------------------------------------
Provisional candidates: 30
Stable strata: 15
Changed strata: 15
Field observations collected: 0
Proposed ecological indicators: 8

5. RESEARCH INTERPRETATION
------------------------------------------------------------------------------
The field-validation framework links 30 provisional sampling
candidates to eight proposed ecological and grazing-management
indicators.

Candidate locations retain their original recovery-stratum
assignments, while seasonal classification stability and review
priority are maintained as separate quality-assurance attributes.

No independent field measurements or authorized grazing records
have been integrated. Consequently, the proposed indicators
cannot yet be used to validate vegetation recovery categories,
attribute observed changes to grazing, or assign agricultural
sustainability ratings.

Subsequent work requires approved field methods, appropriate
Tribal authorization, ecological reference criteria, and
independent observations.

6. REPRODUCIBILITY AND DATA GOVERNANCE
------------------------------------------------------------------------------
Existing candidate coordinates preserved.
Original sampling allocation preserved.
No field measurements invented.
No sustainability ratings assigned.
No files created or modified.
New registers exist only in notebook memory.

SA 17.5.1 COMPLETE

In [122]:

# =============================================================================
# SA 17.5.2 — PROPOSED FIELD MEASUREMENT PROTOCOL AND SAMPLING DESIGN
# Environmental Data Cube for Oglala Lakota
# Ate Makoce - BIA Parcel
#
# PLANNING ONLY:
# - No fieldwork is authorized by this code
# - No observations or sustainability ratings are generated
# - No existing files or notebook objects are overwritten
# - No site coordinates are displayed or exported
# =============================================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 78)
print("SA 17.5.2 — FIELD MEASUREMENT PROTOCOL")
print("=" * 78)

# -------------------------------------------------------------------------
# 1. VERIFY PREVIOUS FRAMEWORK
# -------------------------------------------------------------------------

required = [
    "sa17_5_indicator_register",
    "sa17_5_field_planning_register"
]

missing = [x for x in required if x not in globals()]

if missing:
    raise RuntimeError(
        "Missing prerequisite objects: " + ", ".join(missing)
    )

if any(
    name in globals()
    for name in [
        "sa17_5_2_protocol",
        "sa17_5_2_sampling_design",
        "sa17_5_2_qa",
        "sa17_5_2_governance"
    ]
):
    raise RuntimeError(
        "SA 17.5.2 output objects already exist. "
        "Review them before rerunning to avoid overwriting."
    )

planning = sa17_5_field_planning_register.copy()
indicators = sa17_5_indicator_register.copy()

assert len(planning) == 30, "Expected 30 candidate sites."
assert len(indicators) == 8, "Expected 8 proposed indicators."
assert planning["Candidate_ID"].is_unique
assert indicators["Indicator_ID"].is_unique

expected_strata = {0, 1, 2, 3, 4}

assert set(
    planning["Original_Stratum"].astype(int)
) == expected_strata

stratum_counts = (
    planning.groupby("Original_Stratum")
    .size()
)

assert (stratum_counts == 6).all(), (
    "Original six-per-stratum allocation has changed."
)

assert not planning["Field_Validation_Complete"].fillna(
    False
).astype(bool).any(), (
    "Some sites are marked field-validated; "
    "review status before constructing a planning-only protocol."
)

# -------------------------------------------------------------------------
# 2. DEFINE PROPOSED METHODS
# -------------------------------------------------------------------------

methods = [
    (
        "VEG-01",
        "Line-point intercept",
        "20 m transect; 40 observations at 0.5 m spacing",
        "Percent vegetation hits",
        "Confirm transect orientation and cover categories"
    ),
    (
        "VEG-02",
        "Quadrat biomass sampling",
        "Five 0.25 m2 quadrats per candidate",
        "kg dry matter/ha",
        "Confirm clipping permissions and drying procedure"
    ),
    (
        "VEG-03",
        "Species-level vegetation survey",
        "Record species composition using an approved method",
        "Percent cover by species",
        "Confirm identification and cover estimation protocol"
    ),
    (
        "SOIL-01",
        "Line-point intercept",
        "Use the same transect observations as VEG-01",
        "Percent bare-ground hits",
        "Define bare ground, litter, rock, and vegetation classes"
    ),
    (
        "SOIL-02",
        "Soil surface assessment",
        "Document surface features at each sampling unit",
        "Protocol-defined observations",
        "Select and approve a standardized field assessment"
    ),
    (
        "SOIL-03",
        "Erosion indicator assessment",
        "Document rills, pedestals, and soil movement",
        "Protocol-defined observations",
        "Define observation area and scoring criteria"
    ),
    (
        "GRAZE-01",
        "Forage utilization assessment",
        "Approved utilization protocol only",
        "Percent utilization",
        "Establish reference method and timing"
    ),
    (
        "GRAZE-02",
        "Management records review",
        "Use authorized stocking and grazing records",
        "Record-specific units",
        "Establish access, provenance, and use permissions"
    )
]

method_df = pd.DataFrame(
    methods,
    columns=[
        "Indicator_ID",
        "Proposed_Field_Method",
        "Proposed_Sampling_Design",
        "Measurement_Unit",
        "Protocol_Review_Requirement"
    ]
)

protocol = indicators.merge(
    method_df,
    on="Indicator_ID",
    how="left",
    validate="one_to_one"
)

assert len(protocol) == len(indicators)
assert protocol["Proposed_Field_Method"].notna().all()

protocol["Approval_Status"] = "Proposed — not approved"
protocol["Observation_Status"] = "Not collected"
protocol["Reference_Criteria_Status"] = "Not established"

# -------------------------------------------------------------------------
# 3. BUILD CANDIDATE-LEVEL SAMPLING DESIGN
# -------------------------------------------------------------------------

sampling = planning[
    [
        "Candidate_ID",
        "Original_Stratum",
        "Summer_Stratum",
        "Stratum_Stable",
        "Review_Priority",
        "Site_Authorization"
    ]
].copy()

sampling["Transect_Length_m"] = 20.0
sampling["Line_Point_Spacing_m"] = 0.5
sampling["Proposed_Line_Point_Count"] = 40

sampling["Proposed_Quadrat_Count"] = 5
sampling["Quadrat_Area_m2"] = 0.25

sampling["Transect_Orientation"] = "To be determined"
sampling["Pixel_Footprint_Review"] = "Required"
sampling["GPS_Accuracy_Requirement"] = "To be established"
sampling["Repeat_Visit_Schedule"] = "To be established"

sampling["Sampling_Approval"] = "Pending"
sampling["Field_Observations"] = "Not collected"

sampling["Governance_Check"] = (
    "Tribal authorization and data protocol required"
)

# -------------------------------------------------------------------------
# 4. QUALITY ASSURANCE REGISTER
# -------------------------------------------------------------------------

qa_records = [
    (
        "QA-01",
        "Spatial alignment",
        "Document field footprint relative to Landsat pixel",
        "Pending"
    ),
    (
        "QA-02",
        "GPS quality",
        "Record coordinate reference system and positional accuracy",
        "Pending"
    ),
    (
        "QA-03",
        "Observer consistency",
        "Train observers and conduct repeat measurements",
        "Pending"
    ),
    (
        "QA-04",
        "Vegetation identification",
        "Document species identification and uncertain taxa",
        "Pending"
    ),
    (
        "QA-05",
        "Biomass measurements",
        "Standardize quadrat area, drying, and weighing",
        "Pending"
    ),
    (
        "QA-06",
        "Temporal alignment",
        "Record observation dates and compare with image dates",
        "Pending"
    ),
    (
        "QA-07",
        "Classification sensitivity",
        "Retain original and summer stratum assignments",
        "Pending"
    ),
    (
        "QA-08",
        "Missing observations",
        "Use explicit missing-data codes, never invented zeros",
        "Pending"
    ),
    (
        "QA-09",
        "Independent validation",
        "Separate field observations from satellite classifications",
        "Pending"
    ),
    (
        "QA-10",
        "Data provenance",
        "Document collectors, instruments, methods, and revisions",
        "Pending"
    )
]

qa_register = pd.DataFrame(
    qa_records,
    columns=[
        "QA_ID",
        "QA_Component",
        "Requirement",
        "Status"
    ]
)

# -------------------------------------------------------------------------
# 5. TRIBAL DATA SOVEREIGNTY AND GOVERNANCE
# -------------------------------------------------------------------------

governance_records = [
    (
        "GOV-01",
        "Tribal research authorization",
        "Confirm applicable research approval requirements"
    ),
    (
        "GOV-02",
        "Land access",
        "Obtain permission before entering sampling locations"
    ),
    (
        "GOV-03",
        "Field methods",
        "Approve sampling and specimen collection protocols"
    ),
    (
        "GOV-04",
        "Data stewardship",
        "Identify authorized data stewards and access rules"
    ),
    (
        "GOV-05",
        "Sensitive locations",
        "Restrict exact coordinates where required"
    ),
    (
        "GOV-06",
        "Management records",
        "Establish authorized access and permitted uses"
    ),
    (
        "GOV-07",
        "Publication and sharing",
        "Establish review and disclosure requirements"
    ),
    (
        "GOV-08",
        "Student participation",
        "Document training, supervision, and data responsibilities"
    )
]

governance = pd.DataFrame(
    governance_records,
    columns=[
        "Governance_ID",
        "Requirement",
        "Proposed_Action"
    ]
)

governance["Status"] = "Not documented"

# -------------------------------------------------------------------------
# 6. VALIDATE DESIGN INTEGRITY
# -------------------------------------------------------------------------

assert len(sampling) == 30
assert sampling["Candidate_ID"].is_unique

assert (
    sampling.groupby("Original_Stratum").size() == 6
).all()

assert sampling["Field_Observations"].eq(
    "Not collected"
).all()

assert sampling["Sampling_Approval"].eq(
    "Pending"
).all()

assert protocol["Approval_Status"].eq(
    "Proposed — not approved"
).all()

# -------------------------------------------------------------------------
# 7. SAVE NEW OBJECTS IN NOTEBOOK MEMORY ONLY
# -------------------------------------------------------------------------

sa17_5_2_protocol = protocol.copy()
sa17_5_2_sampling_design = sampling.copy()
sa17_5_2_qa = qa_register.copy()
sa17_5_2_governance = governance.copy()

# -------------------------------------------------------------------------
# 8. DISPLAY RESULTS
# -------------------------------------------------------------------------

print("\n1. PROPOSED FIELD MEASUREMENT PROTOCOL")
print("-" * 78)

display(
    sa17_5_2_protocol[
        [
            "Indicator_ID",
            "Indicator",
            "Proposed_Field_Method",
            "Proposed_Sampling_Design",
            "Approval_Status"
        ]
    ]
)

print("\n2. CANDIDATE SAMPLING DESIGN")
print("-" * 78)

display(
    sa17_5_2_sampling_design[
        [
            "Candidate_ID",
            "Original_Stratum",
            "Stratum_Stable",
            "Transect_Length_m",
            "Proposed_Line_Point_Count",
            "Proposed_Quadrat_Count",
            "Sampling_Approval"
        ]
    ]
)

print("\n3. QUALITY ASSURANCE REGISTER")
print("-" * 78)

display(sa17_5_2_qa)

print("\n4. TRIBAL DATA GOVERNANCE REGISTER")
print("-" * 78)

display(sa17_5_2_governance)

print("\n5. DESIGN SUMMARY")
print("-" * 78)

print(f"Provisional candidates: {len(sampling)}")
print(f"Original strata: {sampling['Original_Stratum'].nunique()}")
print(f"Proposed indicators: {len(protocol)}")
print(f"QA requirements: {len(qa_register)}")
print(f"Governance requirements: {len(governance)}")

print(
    "Stable candidate classifications: "
    f"{int(sampling['Stratum_Stable'].sum())}"
)

print(
    "Changed candidate classifications: "
    f"{int((~sampling['Stratum_Stable']).sum())}"
)

print("\n6. METHODOLOGICAL INTERPRETATION")
print("-" * 78)

print("""
A provisional field measurement protocol has been established
for 30 candidate locations across five original vegetation-
response strata.

The protocol specifies proposed vegetation, soil, and
grazing-management indicators, along with preliminary
transect and quadrat designs.

Sampling dimensions, repeat observations, and spatial
alignment with Landsat pixels require further review.

All field activities remain subject to appropriate Tribal
authorization, land access permissions, approved methods,
and data stewardship requirements.

No field observations have been collected, and no agricultural
sustainability ratings have been assigned.
""".strip())

print("\nSA 17.5.2 COMPLETE")
print("No files created or modified.")
print("Existing candidate coordinates and classifications preserved.")

==============================================================================
SA 17.5.2 — FIELD MEASUREMENT PROTOCOL
==============================================================================

1. PROPOSED FIELD MEASUREMENT PROTOCOL
------------------------------------------------------------------------------

,Indicator_ID,Indicator,Proposed_Field_Method,Proposed_Sampling_Design,Approval_Status
0,VEG-01,Vegetation cover,Line-point intercept,20 m transect; 40 observations at 0.5 m spacing,Proposed — not approved
1,VEG-02,Aboveground forage biomass,Quadrat biomass sampling,Five 0.25 m2 quadrats per candidate,Proposed — not approved
2,VEG-03,Plant species composition,Species-level vegetation survey,Record species composition using an approved m...,Proposed — not approved
3,SOIL-01,Bare ground,Line-point intercept,Use the same transect observations as VEG-01,Proposed — not approved
4,SOIL-02,Soil surface condition,Soil surface assessment,Document surface features at each sampling unit,Proposed — not approved
5,SOIL-03,Visible erosion indicators,Erosion indicator assessment,"Document rills, pedestals, and soil movement",Proposed — not approved
6,GRAZE-01,Forage utilization,Forage utilization assessment,Approved utilization protocol only,Proposed — not approved
7,GRAZE-02,Stocking and grazing history,Management records review,Use authorized stocking and grazing records,Proposed — not approved

2. CANDIDATE SAMPLING DESIGN
------------------------------------------------------------------------------

,Candidate_ID,Original_Stratum,Stratum_Stable,Transect_Length_m,Proposed_Line_Point_Count,Proposed_Quadrat_Count,Sampling_Approval
0,AM-01,0,True,20.0,40,5,Pending
1,AM-02,0,False,20.0,40,5,Pending
2,AM-03,0,False,20.0,40,5,Pending
3,AM-04,0,False,20.0,40,5,Pending
4,AM-05,0,True,20.0,40,5,Pending
5,AM-06,0,False,20.0,40,5,Pending
6,AM-07,1,False,20.0,40,5,Pending
7,AM-08,1,False,20.0,40,5,Pending
8,AM-09,1,False,20.0,40,5,Pending
9,AM-10,1,False,20.0,40,5,Pending
10,AM-11,1,False,20.0,40,5,Pending
11,AM-12,1,False,20.0,40,5,Pending
12,AM-13,2,True,20.0,40,5,Pending
13,AM-14,2,True,20.0,40,5,Pending
14,AM-15,2,True,20.0,40,5,Pending
15,AM-16,2,True,20.0,40,5,Pending
16,AM-17,2,True,20.0,40,5,Pending
17,AM-18,2,True,20.0,40,5,Pending
18,AM-19,3,True,20.0,40,5,Pending
19,AM-20,3,True,20.0,40,5,Pending
20,AM-21,3,True,20.0,40,5,Pending
21,AM-22,3,True,20.0,40,5,Pending
22,AM-23,3,False,20.0,40,5,Pending
23,AM-24,3,True,20.0,40,5,Pending
24,AM-25,4,False,20.0,40,5,Pending
25,AM-26,4,True,20.0,40,5,Pending
26,AM-27,4,False,20.0,40,5,Pending
27,AM-28,4,False,20.0,40,5,Pending
28,AM-29,4,False,20.0,40,5,Pending
29,AM-30,4,True,20.0,40,5,Pending

3. QUALITY ASSURANCE REGISTER
------------------------------------------------------------------------------

,QA_ID,QA_Component,Requirement,Status
0,QA-01,Spatial alignment,Document field footprint relative to Landsat p...,Pending
1,QA-02,GPS quality,Record coordinate reference system and positio...,Pending
2,QA-03,Observer consistency,Train observers and conduct repeat measurements,Pending
3,QA-04,Vegetation identification,Document species identification and uncertain ...,Pending
4,QA-05,Biomass measurements,"Standardize quadrat area, drying, and weighing",Pending
5,QA-06,Temporal alignment,Record observation dates and compare with imag...,Pending
6,QA-07,Classification sensitivity,Retain original and summer stratum assignments,Pending
7,QA-08,Missing observations,"Use explicit missing-data codes, never invente...",Pending
8,QA-09,Independent validation,Separate field observations from satellite cla...,Pending
9,QA-10,Data provenance,"Document collectors, instruments, methods, and...",Pending

4. TRIBAL DATA GOVERNANCE REGISTER
------------------------------------------------------------------------------

,Governance_ID,Requirement,Proposed_Action,Status
0,GOV-01,Tribal research authorization,Confirm applicable research approval requirements,Not documented
1,GOV-02,Land access,Obtain permission before entering sampling loc...,Not documented
2,GOV-03,Field methods,Approve sampling and specimen collection proto...,Not documented
3,GOV-04,Data stewardship,Identify authorized data stewards and access r...,Not documented
4,GOV-05,Sensitive locations,Restrict exact coordinates where required,Not documented
5,GOV-06,Management records,Establish authorized access and permitted uses,Not documented
6,GOV-07,Publication and sharing,Establish review and disclosure requirements,Not documented
7,GOV-08,Student participation,"Document training, supervision, and data respo...",Not documented

5. DESIGN SUMMARY
------------------------------------------------------------------------------
Provisional candidates: 30
Original strata: 5
Proposed indicators: 8
QA requirements: 10
Governance requirements: 8
Stable candidate classifications: 15
Changed candidate classifications: 15

6. METHODOLOGICAL INTERPRETATION
------------------------------------------------------------------------------
A provisional field measurement protocol has been established
for 30 candidate locations across five original vegetation-
response strata.

The protocol specifies proposed vegetation, soil, and
grazing-management indicators, along with preliminary
transect and quadrat designs.

Sampling dimensions, repeat observations, and spatial
alignment with Landsat pixels require further review.

All field activities remain subject to appropriate Tribal
authorization, land access permissions, approved methods,
and data stewardship requirements.

No field observations have been collected, and no agricultural
sustainability ratings have been assigned.

SA 17.5.2 COMPLETE
No files created or modified.
Existing candidate coordinates and classifications preserved.

In [123]:

# =============================================================================
# SA 17.5.3 — FIELD DATA DICTIONARY AND VALIDATION READINESS
# Environmental Data Cube for Oglala Lakota
#
# Planning only — no field data generated or files modified.
# =============================================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 78)
print("SA 17.5.3 — FIELD DATA DICTIONARY AND VALIDATION READINESS")
print("=" * 78)

# -------------------------------------------------------------------------
# 1. VERIFY PREREQUISITES AND PROTECT EXISTING OUTPUTS
# -------------------------------------------------------------------------

required = [
    "sa17_5_2_protocol",
    "sa17_5_2_sampling_design",
    "sa17_5_2_qa",
    "sa17_5_2_governance"
]

missing = [name for name in required if name not in globals()]

if missing:
    raise RuntimeError(
        "Missing prerequisite objects: " + ", ".join(missing)
    )

outputs = [
    "sa17_5_3_dictionary",
    "sa17_5_3_observation_template",
    "sa17_5_3_validation_rules",
    "sa17_5_3_readiness"
]

existing = [name for name in outputs if name in globals()]

if existing:
    raise RuntimeError(
        "Output objects already exist: " + ", ".join(existing)
    )

sampling = sa17_5_2_sampling_design.copy()
protocol = sa17_5_2_protocol.copy()
qa = sa17_5_2_qa.copy()
governance = sa17_5_2_governance.copy()

assert len(sampling) == 30
assert sampling["Candidate_ID"].is_unique
assert len(protocol) == 8

# -------------------------------------------------------------------------
# 2. DEFINE DATA DICTIONARY
# -------------------------------------------------------------------------

fields = [
    # Field, Type, Unit, Description, Requirement
    (
        "Observation_ID", "string", "none",
        "Unique identifier for one field observation",
        "Required when collected"
    ),
    (
        "Candidate_ID", "string", "none",
        "Link to approved sampling candidate",
        "Required when collected"
    ),
    (
        "Visit_ID", "string", "none",
        "Unique field visit identifier",
        "Required when collected"
    ),
    (
        "Observation_Date", "date", "YYYY-MM-DD",
        "Date of independent field observation",
        "Required when collected"
    ),
    (
        "Indicator_ID", "string", "none",
        "Identifier from approved indicator register",
        "Required when collected"
    ),
    (
        "Replicate_ID", "string", "none",
        "Transect, point, or quadrat replicate identifier",
        "Required when applicable"
    ),
    (
        "Observed_Value", "numeric", "indicator-specific",
        "Measured value; missing is not zero",
        "Conditional"
    ),
    (
        "Observed_Category", "string", "protocol-defined",
        "Categorical result where numeric value is unsuitable",
        "Conditional"
    ),
    (
        "Measurement_Unit", "string", "indicator-specific",
        "Unit corresponding to observation",
        "Required for numeric observations"
    ),
    (
        "Method_Version", "string", "none",
        "Approved protocol and version",
        "Required when collected"
    ),
    (
        "Observer_Code", "string", "none",
        "Coded observer identifier",
        "Required when collected"
    ),
    (
        "Instrument_ID", "string", "none",
        "Instrument or equipment identifier",
        "Required when applicable"
    ),
    (
        "GPS_Accuracy_m", "numeric", "m",
        "Reported horizontal positional accuracy",
        "Required for georeferenced observations"
    ),
    (
        "QA_Status", "string", "controlled vocabulary",
        "Pending, Pass, Review, or Fail",
        "Required when collected"
    ),
    (
        "Missing_Reason", "string", "controlled vocabulary",
        "Reason measurement is unavailable",
        "Required when measurement missing"
    ),
    (
        "Authorization_Reference", "string", "restricted reference",
        "Reference to documented field authorization",
        "Required before collection"
    ),
    (
        "Data_Access_Tier", "string", "controlled vocabulary",
        "Approved access classification",
        "Required when collected"
    ),
    (
        "Record_Notes", "string", "none",
        "Relevant field context without sensitive disclosures",
        "Optional"
    )
]

dictionary = pd.DataFrame(
    fields,
    columns=[
        "Field_Name",
        "Data_Type",
        "Unit",
        "Description",
        "Requirement"
    ]
)

assert dictionary["Field_Name"].is_unique

# -------------------------------------------------------------------------
# 3. CREATE EMPTY OBSERVATION TEMPLATE
# -------------------------------------------------------------------------

# Zero rows deliberately: no observations are invented.
observation_template = pd.DataFrame({
    field: pd.Series(dtype="object")
    for field in dictionary["Field_Name"]
})

assert len(observation_template) == 0

# -------------------------------------------------------------------------
# 4. DEFINE VALIDATION RULES
# -------------------------------------------------------------------------

rules = [
    (
        "VAL-01", "Candidate integrity",
        "Candidate_ID must match an approved site identifier"
    ),
    (
        "VAL-02", "Indicator integrity",
        "Indicator_ID must match the indicator register"
    ),
    (
        "VAL-03", "Observation provenance",
        "Record visit, date, observer, and method version"
    ),
    (
        "VAL-04", "Numeric measurement",
        "Require numeric value and appropriate units"
    ),
    (
        "VAL-05", "Missing data",
        "Use missing values with documented reasons; never substitute zero"
    ),
    (
        "VAL-06", "Percent measurements",
        "Percentages must fall between 0 and 100"
    ),
    (
        "VAL-07", "Biomass measurements",
        "Biomass must be nonnegative and use documented dry-matter units"
    ),
    (
        "VAL-08", "Spatial accuracy",
        "Document positional uncertainty and sampling footprint"
    ),
    (
        "VAL-09", "Temporal alignment",
        "Retain actual field and satellite acquisition dates"
    ),
    (
        "VAL-10", "Independence",
        "Do not derive field measurements from satellite classifications"
    ),
    (
        "VAL-11", "Governance",
        "Require authorization and approved access tier before collection"
    ),
    (
        "VAL-12", "Quality assurance",
        "Flag unverified or failed observations; do not silently discard"
    )
]

validation_rules = pd.DataFrame(
    rules,
    columns=[
        "Rule_ID",
        "Component",
        "Validation_Requirement"
    ]
)

validation_rules["Status"] = "Proposed"

# -------------------------------------------------------------------------
# 5. VALIDATION READINESS AUDIT
# -------------------------------------------------------------------------

checks = [
    (
        "Candidate register",
        len(sampling) == 30 and sampling["Candidate_ID"].is_unique
    ),
    (
        "Five original strata",
        sampling["Original_Stratum"].nunique() == 5
    ),
    (
        "Six candidates per stratum",
        sampling.groupby("Original_Stratum").size().eq(6).all()
    ),
    (
        "Eight indicator definitions",
        len(protocol) == 8
    ),
    (
        "Field QA register present",
        len(qa) == 10
    ),
    (
        "Governance register present",
        len(governance) == 8
    ),
    (
        "Field methods approved",
        protocol["Approval_Status"].eq("Approved").all()
    ),
    (
        "Site authorization documented",
        sampling["Site_Authorization"].eq("Approved").all()
    ),
    (
        "Sampling approval documented",
        sampling["Sampling_Approval"].eq("Approved").all()
    ),
    (
        "Governance requirements documented",
        governance["Status"].eq("Approved").all()
    )
]

readiness = pd.DataFrame(
    checks,
    columns=["Readiness_Check", "Satisfied"]
)

readiness["Status"] = np.where(
    readiness["Satisfied"],
    "Satisfied",
    "Pending"
)

# -------------------------------------------------------------------------
# 6. STORE NEW OBJECTS IN MEMORY
# -------------------------------------------------------------------------

sa17_5_3_dictionary = dictionary.copy()
sa17_5_3_observation_template = observation_template.copy()
sa17_5_3_validation_rules = validation_rules.copy()
sa17_5_3_readiness = readiness.copy()

# -------------------------------------------------------------------------
# 7. REPORT
# -------------------------------------------------------------------------

print("\n1. FIELD DATA DICTIONARY")
print("-" * 78)
display(sa17_5_3_dictionary)

print("\n2. EMPTY OBSERVATION TEMPLATE")
print("-" * 78)
print("Rows:", len(sa17_5_3_observation_template))
print(
    "Columns:",
    len(sa17_5_3_observation_template.columns)
)
print(
    "No field observations have been generated."
)

print("\n3. VALIDATION RULES")
print("-" * 78)
display(sa17_5_3_validation_rules)

print("\n4. VALIDATION READINESS")
print("-" * 78)
display(sa17_5_3_readiness)

print("\n5. SUMMARY")
print("-" * 78)
print("Data dictionary fields:", len(dictionary))
print("Validation rules:", len(validation_rules))
print("Provisional candidates:", len(sampling))
print("Actual field observations:", len(observation_template))
print(
    "Readiness checks satisfied:",
    int(readiness["Satisfied"].sum()),
    "of",
    len(readiness)
)

ready_for_fieldwork = bool(readiness["Satisfied"].all())

print("Fieldwork readiness:", (
    "All listed checks satisfied; final authorization review required"
    if ready_for_fieldwork
    else "NOT READY — approvals or documentation pending"
))

print("\nSA 17.5.3 COMPLETE")
print("No files created or modified.")
print("No sensitive site coordinates displayed.")

==============================================================================
SA 17.5.3 — FIELD DATA DICTIONARY AND VALIDATION READINESS
==============================================================================

1. FIELD DATA DICTIONARY
------------------------------------------------------------------------------

,Field_Name,Data_Type,Unit,Description,Requirement
0,Observation_ID,string,none,Unique identifier for one field observation,Required when collected
1,Candidate_ID,string,none,Link to approved sampling candidate,Required when collected
2,Visit_ID,string,none,Unique field visit identifier,Required when collected
3,Observation_Date,date,YYYY-MM-DD,Date of independent field observation,Required when collected
4,Indicator_ID,string,none,Identifier from approved indicator register,Required when collected
5,Replicate_ID,string,none,"Transect, point, or quadrat replicate identifier",Required when applicable
6,Observed_Value,numeric,indicator-specific,Measured value; missing is not zero,Conditional
7,Observed_Category,string,protocol-defined,Categorical result where numeric value is unsu...,Conditional
8,Measurement_Unit,string,indicator-specific,Unit corresponding to observation,Required for numeric observations
9,Method_Version,string,none,Approved protocol and version,Required when collected
10,Observer_Code,string,none,Coded observer identifier,Required when collected
11,Instrument_ID,string,none,Instrument or equipment identifier,Required when applicable
12,GPS_Accuracy_m,numeric,m,Reported horizontal positional accuracy,Required for georeferenced observations
13,QA_Status,string,controlled vocabulary,"Pending, Pass, Review, or Fail",Required when collected
14,Missing_Reason,string,controlled vocabulary,Reason measurement is unavailable,Required when measurement missing
15,Authorization_Reference,string,restricted reference,Reference to documented field authorization,Required before collection
16,Data_Access_Tier,string,controlled vocabulary,Approved access classification,Required when collected
17,Record_Notes,string,none,Relevant field context without sensitive discl...,Optional

2. EMPTY OBSERVATION TEMPLATE
------------------------------------------------------------------------------
Rows: 0
Columns: 18
No field observations have been generated.

3. VALIDATION RULES
------------------------------------------------------------------------------

,Rule_ID,Component,Validation_Requirement,Status
0,VAL-01,Candidate integrity,Candidate_ID must match an approved site ident...,Proposed
1,VAL-02,Indicator integrity,Indicator_ID must match the indicator register,Proposed
2,VAL-03,Observation provenance,"Record visit, date, observer, and method version",Proposed
3,VAL-04,Numeric measurement,Require numeric value and appropriate units,Proposed
4,VAL-05,Missing data,Use missing values with documented reasons; ne...,Proposed
5,VAL-06,Percent measurements,Percentages must fall between 0 and 100,Proposed
6,VAL-07,Biomass measurements,Biomass must be nonnegative and use documented...,Proposed
7,VAL-08,Spatial accuracy,Document positional uncertainty and sampling f...,Proposed
8,VAL-09,Temporal alignment,Retain actual field and satellite acquisition ...,Proposed
9,VAL-10,Independence,Do not derive field measurements from satellit...,Proposed
10,VAL-11,Governance,Require authorization and approved access tier...,Proposed
11,VAL-12,Quality assurance,Flag unverified or failed observations; do not...,Proposed

4. VALIDATION READINESS
------------------------------------------------------------------------------

                      Readiness_Check  Satisfied     Status
0                  Candidate register       True  Satisfied
1                Five original strata       True  Satisfied
2          Six candidates per stratum       True  Satisfied
3         Eight indicator definitions       True  Satisfied
4           Field QA register present       True  Satisfied
5         Governance register present       True  Satisfied
6              Field methods approved      False    Pending
7       Site authorization documented      False    Pending
8        Sampling approval documented      False    Pending
9  Governance requirements documented      False    Pending

5. SUMMARY
------------------------------------------------------------------------------
Data dictionary fields: 18
Validation rules: 12
Provisional candidates: 30
Actual field observations: 0
Readiness checks satisfied: 6 of 10
Fieldwork readiness: NOT READY — approvals or documentation pending

SA 17.5.3 COMPLETE
No files created or modified.
No sensitive site coordinates displayed.